- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
      - npm
    state: present

- name: Add App user
  user:
    name: roboshop
    comment: RoboShop user

- name: Make App Directory
  shell: mkdir -p /home/roboshop/catalogue

- name: Download Component files
  copy: 
    src: files/
    dest: /home/roboshop/catalogue

- name: Download NodeJS dependencies
  shell: npm install
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  #become_user: roboshop

# - name: Installing NodeJS dependencies
#   shell: |
#     cd /home/roboshop/{{COMPONENT}}
#     npm install

# - name: Installing NodeJS dependencies
#   npm:
#     path: /home/roboshop/{{COMPONENT}}
#     state: latest

- name: Add {{COMPONENT}} service file
  template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Enamble/Start {{COMPONENT}} services
  systemd:
    daemon_reload: yes
    enabled: yes
    name: catalogue
    state: restarted 